window_width = 1080
window_height = 800
window_title = SDL Playground
window_fullscreen = false
chunk_space_width = 1
chunk_space_height = 1
region_width = 3
region_height = 3
chunk_width = 64
chunk_height = 64
clear_color = 0xFF181818
icon_image_path = ./src/images/sand.bmp
heatmap_mode = false
frame_keep_enabled = true
frame_keep = 60
brush_size = 3