[window]
window_title = "SDL Playground"
window_width = 720
window_height = 480
window_fullscreen = true
icon_image_path = "./resources/sand.bmp"

clear_color = "0x00181818"

frame_lock_enabled = true
frame_lock = 60

[chunk]
chunk_space_width = 1
chunk_space_height = 1
region_width = 3
region_height = 3
chunk_width = 64
chunk_height = 64
