#ifndef CONSTANTS_H
#define CONSTANTS_H

// #define DEFAULT_CHUNK_LOAD_DISTANCE 3
// #define DEFAULT_CHUNK_SIMULATION_DISTANCE 4
// #define DEFAULT_CHUNK_SIZE 64
// #define DEFAULT_PARTICLE_SIZE 2

extern const int DEFAULT_CHUNK_LOAD_DISTANCE;
extern const int DEFAULT_CHUNK_SIMULATION_DISTANCE;
extern const int DEFAULT_CHUNK_SIZE;
extern const int DEFAULT_PARTICLE_SIZE;


#endif //CONSTANTS_H