#ifndef CONSTANTS_H
#define CONSTANTS_H

#define DEFAULT_CHUNK_LOAD_DISTANCE 3
#define DEFAULT_CHUNK_SIMULATION_DISTANCE 4
#define DEFAULT_CHUNK_SIZE 256
#define DEFAULT_PARTICLE_SIZE 1


#endif //CONSTANTS_H