#ifndef CONSTANTS_H
#define CONSTANTS_H

#define DEFAULT_CHUNK_LOAD_DISTANCE 3
#define DEFAULT_CHUNK_SIMULATION_DISTANCE 4
#define DEFAULT_CHUNK_SIZE 64
#define DEFAULT_PARTICLE_SIZE 4


#endif //CONSTANTS_H