[window]
window_title = ""
window_width = 720
window_height = 480
window_fullscreen = false
icon_image_path = ""
window_visible = false
window_render_api = "renderer"

clear_color = "0x00181818"

frame_lock_enabled = true
frame_lock = 60
